<?php include("count.php"); ?>
<!DOCTYPE html
	PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	 "http://www.w3.org/TR/html4/loose.dtd">
<html><head><title>ELRC-5136-Tuarasclacha_Bliantl</title>
<link rev="made" href="mailto:Joerg%20Tiedemann">

<meta name="robots" content="NOFOLLOW">
<link rel="stylesheet" type="text/css" href="index.css">
</head>
<body>
<div class="header"><?php include("header.php"); ?></div><h1>ELRC-5136-Tuarasclacha_Bliantl v1</h1>Tuarascálacha Bliantúla ó Choláiste na Tríonóide, Baile Átha Cliath   <p>2 languages, total number of files: 2<br>total number of tokens: 62.63k<br>total number of sentence fragments: 2.91k<br><p>Please acknowledge the <a href="https://elrc-share.eu/repository/browse/tuarascalacha-bliantula-o-cholaiste-na-trionoide-baile-atha-cliath/4a33b87a8f0911ec9c1a00155d026706555ac13e9e99414d97931a04ff96db1c/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)<h3>Download</h3><p>Below you can download data files for all language pairs in different formats and with different kind of annotation (if available). You can click on the various links as explained below. In addition to the files shown on this webpage, OPUS also provides pre-compiled word alignments and phrase tables, bilingual dictionaries, frequency counts, and these files can be found through the <a href="/index.php">resources search form on the top-level website of OPUS</a>.</p><p><b>License:</b> openUnder-PSIopenUnder-PSI<br/><b>Copyright:</b> Check details at <a href="https://elrc-share.eu/repository/browse/tuarascalacha-bliantula-o-cholaiste-na-trionoide-baile-atha-cliath/4a33b87a8f0911ec9c1a00155d026706555ac13e9e99414d97931a04ff96db1c/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a><br/></p>ELRC-5136-Tuarascálacha_Bliantúla_ó_Choláiste_na_Tríonóide_Baile_Átha_Cliath is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/tuarascalacha-bliantula-o-cholaiste-na-trionoide-baile-atha-cliath/4a33b87a8f0911ec9c1a00155d026706555ac13e9e99414d97931a04ff96db1c/">https://www.elrc-share.eu</a><h3>Release history:</h3><p><ul><li><a href="ELRC-5136-Tuarasclacha_Bliantl-v1.php">ELRC-5136-Tuarasclacha_Bliantl v1</a></li></ul></p><table><tr><td>Bottom-left triangle: download files<ul><li><i>ces</i> = sentence alignments in XCES format</li> <li><i>leftmost column language IDs</i> = tokenized corpus files in XML</li> <li>TMX and plain text files (Moses): see "Statistics" below</li> <li><i>lower row language IDs</i> = parsed corpus files (if they exist)</li></ul></td><td>Upper-right triangle: sample files <ul><li><i>view</i> = bilingual XML file samples</li> <li><i>upper row language IDs</i> = monolingual XML file samples</li> <li><i>rightmost column language IDs</i> = untokenized corpus files</li></ul></td></tr></table><p><div class="sample"><table border="0" cellpadding="0">
<tr>
<th></th>
<th><a rel="nofollow" href="ELRC-5136-Tuarasclacha_Bliantl/v1/en_sample.html">en</a></th>
<th><a rel="nofollow" href="ELRC-5136-Tuarasclacha_Bliantl/v1/ga_sample.html">ga</a></th>
<th></th></tr>
<tr><th><a rel="nofollow" href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/xml/en.zip">en</a></th>
<th></th>
<td><a rel="nofollow" title="English-Irish (sample file)" href="ELRC-5136-Tuarasclacha_Bliantl/v1/en-ga_sample.html">view</a></td><th><a rel="nofollow" href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/raw/en.zip">en</a></th></tr>
<tr><th><a rel="nofollow" href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/xml/ga.zip">ga</a></th>
<td><a rel="nofollow" title="sentence alignments for 'Irish-English' (1.0k links, 62.6k tokens)" href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/xml/en-ga.xml.gz">ces</a></td>
<th></th>
<th><a rel="nofollow" href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/raw/ga.zip">ga</a></th></tr>
<tr><th></th>
<th>en</th>
<th>ga</th>
<th></th></tr>
</table>
</div><p><h3>Statistics and TMX/Moses Downloads</h3>Number of files, tokens, and sentences per language (including non-parallel ones if they exist)<br>Number of sentence alignment units per language pair<p>Upper-right triangle: download translation memory files (TMX)<br>Bottom-left triangle: download plain text files (MOSES/GIZA++)<br>Language ID's, first row: monolingual plain text files (tokenized)<br>Language ID's, first column: monolingual plain text files (untokenized)<div class="counts"><table><caption></caption> <tr><th>language</th> <th>files</th> <th>tokens</th> <th>sentences</th><th><a rel="nofollow" title='monolingual tokenized en plain text' href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/mono/en.tok.gz">en</a>
</th><th><a rel="nofollow" title='monolingual tokenized ga plain text' href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/mono/ga.tok.gz">ga</a>
</th></tr> <tr><th><a rel="nofollow" title='monolingual untokenized en plain text' href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/mono/en.txt.gz">en</a>
</th><td>1</td> <td>28.3k</td> <td>1.4k</td><td></td><td bgcolor="#ffd7d7"><a rel="nofollow" title='English-Irish (1,037 sentence pairs, 55.09k words) - TMX format' href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/tmx/en-ga.tmx.gz">1.0k</a>
</td></tr> <tr><th><a rel="nofollow" title='monolingual untokenized ga plain text' href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/mono/ga.txt.gz">ga</a>
</th><td>1</td> <td>34.4k</td> <td>1.5k</td><td bgcolor="#ffd7d7"><a rel="nofollow" title='Irish-English (1,037 sentence pairs, 55.09k words) - Moses format' href="download.php?f=ELRC-5136-Tuarasclacha_Bliantl/v1/moses/en-ga.txt.zip">1.0k</a>
</td><td></td></tr></table></div><p>Note that TMX files only contain unique translation units and, therefore, the number of aligned units is smaller than for the distributions in Moses and XML format. Moses downloads include all non-empty alignment units including duplicates. Token counts for each language also include duplicate sentences and documents.<p><hr><h3>Disclaimer</h3> <ul> <li>We do not own any of the text from which the data has been extracted.</li> <li>We only offer files that we believe we are free to redistribute. If any doubt occurs about the legality of any of our file downloads we will take them off right away after contacting us.</li> </ul> <h3>Notice and take down policy</h3> Notice: Should you consider that our data contains material that is owned by you and should therefore not be reproduced here, please: <ul> <li>Clearly identify yourself, with detailed contact data such as an address, telephone number or email address at which you can be contacted.</li> <li>Clearly identify the copyrighted work claimed to be infringed.</li> <li>Clearly identify the material that is claimed to be infringing and information reasonably sufficient to allow us to locate the material.</li> <li>And contact the OPUS project at the following email address: opus-project at helsinki.fi.</li> </ul> Take down: We will comply to legitimate requests by removing the affected sources from the next release of the corpus.<div class="footer"></div>
</body>
</html>