<?php include("count.php"); ?>
<!DOCTYPE html
	PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	 "http://www.w3.org/TR/html4/loose.dtd">
<html><head><title>ELRC-488-Justice_Slovak</title>
<link rev="made" href="mailto:Joerg%20Tiedemann">

<meta name="robots" content="NOFOLLOW">
<link rel="stylesheet" type="text/css" href="index.css">
</head>
<body>
<div class="header"><?php include("header.php"); ?></div><h1>ELRC-488-Justice_Slovak v1</h1>English-Slovak parallel corpus of texts from The Ministry of Justice of the Slovak Republic (Processed)   <p>2 languages, total number of files: 2<br>total number of tokens: 0.13M<br>total number of sentence fragments: 6.53k<br><p>Please acknowledge the <a href="https://elrc-share.eu/repository/browse/english-slovak-parallel-corpus-of-texts-from-the-ministry-of-justice-of-the-slovak-republic-processed/ed7c34a6d11e11e7b7d400155d0267060342e920f873481cac9ea8c7406f65b6/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)<h3>Download</h3><p>Below you can download data files for all language pairs in different formats and with different kind of annotation (if available). You can click on the various links as explained below. In addition to the files shown on this webpage, OPUS also provides pre-compiled word alignments and phrase tables, bilingual dictionaries, frequency counts, and these files can be found through the <a href="/index.php">resources search form on the top-level website of OPUS</a>.</p><p><b>License:</b> publicDomainpublicDomain<br/><b>Copyright:</b> Check details at <a href="https://elrc-share.eu/repository/browse/english-slovak-parallel-corpus-of-texts-from-the-ministry-of-justice-of-the-slovak-republic-processed/ed7c34a6d11e11e7b7d400155d0267060342e920f873481cac9ea8c7406f65b6/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a><br/></p>ELRC-488-Justice_Slovak is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/english-slovak-parallel-corpus-of-texts-from-the-ministry-of-justice-of-the-slovak-republic-processed/ed7c34a6d11e11e7b7d400155d0267060342e920f873481cac9ea8c7406f65b6/">https://www.elrc-share.eu</a><h3>Release history:</h3><p><ul><li><a href="ELRC-488-Justice_Slovak-v1.php">ELRC-488-Justice_Slovak v1</a></li></ul></p><table><tr><td>Bottom-left triangle: download files<ul><li><i>ces</i> = sentence alignments in XCES format</li> <li><i>leftmost column language IDs</i> = tokenized corpus files in XML</li> <li>TMX and plain text files (Moses): see "Statistics" below</li> <li><i>lower row language IDs</i> = parsed corpus files (if they exist)</li></ul></td><td>Upper-right triangle: sample files <ul><li><i>view</i> = bilingual XML file samples</li> <li><i>upper row language IDs</i> = monolingual XML file samples</li> <li><i>rightmost column language IDs</i> = untokenized corpus files</li></ul></td></tr></table><p><div class="sample"><table border="0" cellpadding="0">
<tr>
<th></th>
<th><a rel="nofollow" href="ELRC-488-Justice_Slovak/v1/en_sample.html">en</a></th>
<th><a rel="nofollow" href="ELRC-488-Justice_Slovak/v1/sk_sample.html">sk</a></th>
<th></th></tr>
<tr><th><a rel="nofollow" href="download.php?f=ELRC-488-Justice_Slovak/v1/xml/en.zip">en</a></th>
<th></th>
<td><a rel="nofollow" title="English-Slovak (sample file)" href="ELRC-488-Justice_Slovak/v1/en-sk_sample.html">view</a></td><th><a rel="nofollow" href="download.php?f=ELRC-488-Justice_Slovak/v1/raw/en.zip">en</a></th></tr>
<tr><th><a rel="nofollow" href="download.php?f=ELRC-488-Justice_Slovak/v1/xml/sk.zip">sk</a></th>
<td><a rel="nofollow" title="sentence alignments for 'Slovak-English' (2.9k links, 0.1M tokens)" href="download.php?f=ELRC-488-Justice_Slovak/v1/xml/en-sk.xml.gz">ces</a></td>
<th></th>
<th><a rel="nofollow" href="download.php?f=ELRC-488-Justice_Slovak/v1/raw/sk.zip">sk</a></th></tr>
<tr><th></th>
<th>en</th>
<th>sk</th>
<th></th></tr>
</table>
</div><p><h3>Statistics and TMX/Moses Downloads</h3>Number of files, tokens, and sentences per language (including non-parallel ones if they exist)<br>Number of sentence alignment units per language pair<p>Upper-right triangle: download translation memory files (TMX)<br>Bottom-left triangle: download plain text files (MOSES/GIZA++)<br>Language ID's, first row: monolingual plain text files (tokenized)<br>Language ID's, first column: monolingual plain text files (untokenized)<div class="counts"><table><caption></caption> <tr><th>language</th> <th>files</th> <th>tokens</th> <th>sentences</th><th><a rel="nofollow" title='monolingual tokenized en plain text' href="download.php?f=ELRC-488-Justice_Slovak/v1/mono/en.tok.gz">en</a>
</th><th><a rel="nofollow" title='monolingual tokenized sk plain text' href="download.php?f=ELRC-488-Justice_Slovak/v1/mono/sk.tok.gz">sk</a>
</th></tr> <tr><th><a rel="nofollow" title='monolingual untokenized en plain text' href="download.php?f=ELRC-488-Justice_Slovak/v1/mono/en.txt.gz">en</a>
</th><td>1</td> <td>72.9k</td> <td>3.2k</td><td></td><td bgcolor="#ffe0de"><a rel="nofollow" title='English-Slovak (2,636 sentence pairs, 0.13M words) - TMX format' href="download.php?f=ELRC-488-Justice_Slovak/v1/tmx/en-sk.tmx.gz">2.6k</a>
</td></tr> <tr><th><a rel="nofollow" title='monolingual untokenized sk plain text' href="download.php?f=ELRC-488-Justice_Slovak/v1/mono/sk.txt.gz">sk</a>
</th><td>1</td> <td>59.7k</td> <td>3.4k</td><td bgcolor="#ffe0de"><a rel="nofollow" title='Slovak-English (2,896 sentence pairs, 0.13M words) - Moses format' href="download.php?f=ELRC-488-Justice_Slovak/v1/moses/en-sk.txt.zip">2.9k</a>
</td><td></td></tr></table></div><p>Note that TMX files only contain unique translation units and, therefore, the number of aligned units is smaller than for the distributions in Moses and XML format. Moses downloads include all non-empty alignment units including duplicates. Token counts for each language also include duplicate sentences and documents.<p><hr><h3>Disclaimer</h3> <ul> <li>We do not own any of the text from which the data has been extracted.</li> <li>We only offer files that we believe we are free to redistribute. If any doubt occurs about the legality of any of our file downloads we will take them off right away after contacting us.</li> </ul> <h3>Notice and take down policy</h3> Notice: Should you consider that our data contains material that is owned by you and should therefore not be reproduced here, please: <ul> <li>Clearly identify yourself, with detailed contact data such as an address, telephone number or email address at which you can be contacted.</li> <li>Clearly identify the copyrighted work claimed to be infringed.</li> <li>Clearly identify the material that is claimed to be infringing and information reasonably sufficient to allow us to locate the material.</li> <li>And contact Joerg Tiedemann at the following email address: jorg.tiedemann at helsinki.fi.</li> </ul> Take down: We will comply to legitimate requests by removing the affected sources from the next release of the corpus.<div class="footer"></div>
</body>
</html>